just := just_executable()

cargo := env_var_or_default("CARGO", "cargo")

@_default:
    {{just}} --list

# Ensure `rust` tooling is present
@_ensure-tool-cargo:
    command -v {{cargo}} || echo "cargo is not installed, please install it (see: https://doc.rust-lang.org/cargo/getting-started/installation.html)"

# Ensure required tooling is installed
check: _ensure-tool-rust

# Build the `guest reconciler` Rust WebAssembly component
build: check
    {{cargo}} component build --release
